name: EV_DRL
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.8.16
  - matplotlib
  - imageio
  - imageio-ffmpeg
  - tqdm
  - pip=21
  - pip:
      - wandb
      - setuptools==65.5.0
      - wheel==0.38.0
      - stable_baselines3==1.8.0
      - gym==0.21.0